# modules/key-pair/outputs.tf

output "private_key_pem" {
  description = "Private key PEM (sensitive) when generated by the module"
  value       = var.generate_key ? try(tls_private_key.access_key[0].private_key_pem, "") : ""
  sensitive   = true
}

output "private_key_file_path" {
  description = "Local path where private key was written (if enabled)"
  value       = var.write_private_key_file && var.generate_key ? var.private_key_path : ""
}

output "key_pair_name" {
  description = "Name of the SSH key pair"
  value       = var.key_name
}
