# modules/vpn/self-managed/outputs.tf

output "openvpn_ens5_ip" {
  value = "10.0.4.110/24"
}

output "connect_string" {
  value = aws_instance.this.id != "" ? "ssh -i '~/.ssh/ae/${var.key_name}.pem' ubuntu@vpn.${data.aws_route53_zone.this.name}" : null
  # value = aws_instance.this.id != "" ? "ssh -i '~/.ssh/ae/${var.key_name}.pem' ubuntu@${aws_instance.this.public_ip}" : null
  # value = "ssh -i '~/.ssh/ae/5353-eu-west-3.pem' ubuntu@${aws_eip.ec2.address}"
}

output "private_key_pem" {
  description = "Private key PEM (sensitive) when generated by the module"
  value       = var.generate_key ? try(tls_private_key.vpn_key[0].private_key_pem, "") : ""
  sensitive   = true
}

output "private_key_file_path" {
  description = "Local path where private key was written (if enabled)"
  value       = var.write_private_key_file && var.generate_key ? var.private_key_path : ""
}
